services:
  mysql:
    container_name: 'mysql_scheduled'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=scheduled'
      - 'MYSQL_PASSWORD=12345'
      - 'MYSQL_ROOT_PASSWORD=12345'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'